language: node_js
node_js: lts/*
script: npm run build
env:
  global:
    secure: bQvvoajwglRoazXenlj5iXC67mpxXzBjSj2gdzAPaoqUbFkfixgGcwATgQ35/Kf5kX94NdB8xWuuOlJ1sPDfcYxKpz177qa4ReJ49eWcsezSVW2e7blzWCU670rVzAh5E/3YdNdbGlvHCSbnjprOrqFLGBzmtIzRXEAR95i8o/doSe+otHWgpBMwK732k0EOnyEm1BtC7Exqrt9Izp9n50JEo4tMgw9CGz/1KVpcYnoUCrQFFqE3UBf9zZfJJ9fFHqtFwp4WxAIa5yEaXfG95mSUiJ3ePakMTB0W9aNp1Ke0hvJJaAtN9PdFddIlwCzgReCFDcTnopJ3lLigJJET+fCcZSokXAAr72UlqPX1kopgKHhd7RR26mvZ+ewA8Y7hWKHgx8Uv+r6UL0q5wWwxFYNE9hLZxDcifYC8s4djICgR0GrT4iWkcwLSDh0mQP51FPUnNtGydfKAwLjdw/S+dQWc6KHHIhD2+UVfjjyLBHYgSRx1nfClfXVIEV/h/CVTLZmutlpV7/05D4zh4a4dNHAjZgcswZih4oO3K5Kmz/zFrOXMuH7fCuUI8yzagv2T2iC3Gq9jm0xgLvhGFjeji922wvo81IRgdDkteuYXHPwH0jezz1q6ZUyXSDTgpvIDTR4VPUjqAKmKzr4rskeeDV0NO85mTG7pg1akZtpxl3Y=
