language: node_js
node_js: lts/*
script: npm run build
before_deploy: 
  - npm run export
  - npm i -g firebase-tools
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: TB+6qfI7B0CnTvNgMWksLghUWK93DELBHCnZhZXgyNaBiHZ4v/b6qPe1uYv+PumwT/qeEMzolCjSsDTX/aYKAmLySGbP56opx1IDIQY1GjrPcMxOALQ160q0lGgOUVhLbrf3mtPWDpCjrER/6yehBhcpNxqOQqY5BOU3V4ghQkXfiE79lOFrL562Bd8DAfFLw5MspMzDt92sYUmNMgGLktI2/lfI4msgj5yEXzTaXkRRs00U/33btaFOzC3dVOjbA9nOcPzjI3lT3276nCfjcI5m/xufWVQ8zmqRegMNR98QBGCloRxcMVcZSL/Am3J8Mivtg3qyZZ+pvwoMstaSRRINxnGDTdqdSVx1wtYpwAnvWW20LXQeJWoYJNxLx5caWZU3IXPrPXL5mBpQcveMuI4J324eqhs+p75/XX0e3fVyqDvtmlNcdu58JGONKG+L9a6oUPTd7nP8XgV1mbt9mwf4taSlzH8vZvLtCvOYPvldmfoX14J8Mo0KHnJKUMYZt1Md2O01bShqQ8LE3N2RAf2N/OdrRsVNmOTFUZ63hZnljwB0M91Nd9UjDtXMWINGG4KOIRrSECb6XGGYwNpzXbyzMC672UVWimFQE88TUtYwd1siTjgY5hybrVZCC4bDP0V7SCTcPskZImnwIPK0YRnlG+HagP5iTniyAeDcHvk=


