language: node_js
node_js: lts/*
script: npm run build
before_deploy:
- npm run export
- npm i -g firebase-tools
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "COvY9xE0DUdzBOsI5efh/CRStc/X8os9VsE648H2dxdEGgm/cNHumTSxJMBRLTH+ncTI6iDfMLilceoQe25wxMmSjY7fhwz0TNYqOvTykZ2tX+Pu1vrLIuoetMXrV2Xt9N31Y5iyb/DxbADCI8/PYoOIoZHfdC0RsGnPxTFTqWOgTQJbi3v58gXlYKpoHuBszPRlCy5iD5Wxnzq+RhvjzPSooy31VH4l1IWWhJooppe8huYsHLUu2lkogQrX0nlRytINCTs55K9qWEG62dX7jnaDe8vwKECNf8oMpsEbhWlT6zTILxBcgtrYG+VkCB1W6uCEbLYo6UQBSZI6HorUu0+FJcROsp7HMcHwjljJQ8GX90ajgCMFaLNYFGGAMOZeet56eRfLONocLZhyZTHOHuHxiqly5s7IvXTHmJEo7LQW2BU8WNIOeWeVf/VVUeFbuXtV1Gv0g2KbXoblxWzMfxQ2pZiZSm+2usMYk4arlIhQb7q6WzGdF0lyanSamDOoEKM78y7t61lgrZPsvdgLDfZJiWeLHdxpHFg3uzUTBeYGHYtsceu+SGHVc4UKKJj9uYNiXOaKVD+EDOxooO+6SdeDPqPQGLgo+KfU/PVoY8ABsA1mqw8Qe4gXAtJMphirV4O5FSNqeCjfKoF+TPnamRA3kbCm8VtH6M+Nw/l3bu0="